<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class S05_ssw_model extends CI_Model
{

    public $table = 's05_ssw';
    public $id = 'idssw';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idssw', $q);
	$this->db->or_like('NIS', $q);
	$this->db->or_like('Nama', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idssw', $q);
	$this->db->or_like('NIS', $q);
	$this->db->or_like('Nama', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    // buat NIS baru
    function get_new_NIS() {
      // cari nis terakhir
      //$kodeSekolah = $this->session->userdata("kodesekolah");
      $q = "select NIS from s05_ssw where left(NIS, 2) = '".$this->session->userdata('kode_sklh')."' order by NIS desc"; //echo $s;
      $r = $this->db->query($q);
      $count = $r->num_rows();
      if ($count > 0) {
        // sudah ada data
        $row = $r->row();
        $last_NIS = $row->NIS;
        $last_no_urut = substr($last_NIS, 4, 4);
        $next_no_urut = $last_no_urut + 1;
        $next_NIS = $this->session->userdata('kode_sklh') . substr($this->session->userdata('tahun_ajaran'), 2, 2) . sprintf('%04s', $next_no_urut);
      }
      else {
        // belum ada data
        $next_NIS = $this->session->userdata('kode_sklh') . substr($this->session->userdata('tahun_ajaran'), 2, 2) . '0001';
      }
      return $next_NIS;
    }

}

/* End of file S05_ssw_model.php */
/* Location: ./application/models/S05_ssw_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-08-06 00:01:42 */
/* http://harviacode.com */
